version: '2.2'

services:
  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://localhost:5000
      LOGSTASH_TAGS: docker-elk
    network_mode: "host"
    depends_on:
      - logstash
    restart: always
