## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://localhost:9200
elasticsearch.requestTimeout: 90000

sentinl:
  settings:
    email:
      active: true
      user: account@mail.com
      password: XXXXXX
      host: smtp.exmail.qq.com
      ssl: false
      timeout: 10000
    report:
      active: false
#      tmp_path: /tmp/
