## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
#
http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline

pipeline.workers: 4 # 设置成 cpu 核数或者其倍数
pipeline.output.workers: 4
pipeline.batch.size: 1000
pipeline.batch.delay: 10
